gym/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Auth::routes();
Route::get('/', function () {
    return view('welcome');
})->name('land');


//auth
Route::GET('/register','Auth\memberRegisterController@viewregisterform')->name('register');
Route::POST('/register','Auth\memberRegisterController@register')->name('register.submit');


Route::prefix('admin')->name('admin.')->group(function()                //route for all admin
{  
    Route::get('/login','Auth\adminLoginController@showLoginform')->name('login');
    Route::Post('/login','Auth\adminLoginController@login')->name('login.submit');
    Route::get('/logout','Auth\adminLoginController@adminlogout')->name('logout');   
    Route::get('/dashboard','adminController@dashboard')->name('dashboard');

    Route::get('/addgym','adminController@addg')->name('addg');         //addgym 
    Route::Post('/addgym','adminController@addgym')->name('addgym');

    //gym
    Route::get('/activegym','adminController@activegym')->name('activegym');    //list active gym
    Route::get('/allgym','adminController@allgym')->name('allgym');             //list all gym
    Route::get('/gymview/{gym}','adminController@gymview')->name('gymview');    //gymview
    Route::get('/edit/{gym}','adminController@gedit')->name('agym.edit');
    Route::PUT('/update/{gym}','adminController@gupdate')->name('agym.update');
    Route::post('/changepasswordgym/{id}','adminController@passwordupdate')->name('password.update');
    Route::DELETE('/deletegym/{id}','adminController@gymhakai')->name('gym.hakai');

    Route::get('/allmembers/{id}','adminController@allmembers')->name('gym.allmembers');
    Route::get('/memview/{member}','adminController@memberview')->name('member.view');

    Route::get('/adminprofile','adminController@profile')->name('profile');
    Route::post('/adminprofile1','adminController@profileupdate')->name('profile.update');
    Route::get('/future','adminController@future')->name('future');
  

});

Route::prefix('member')->name('member.')->group(function()                //route for all member
{
    Route::get('/login','Auth\memberLoginController@showLoginform')->name('login');
    Route::Post('/login','Auth\memberLoginController@login')->name('login.submit');
    Route::get('/logout','Auth\memberLoginController@memberlogout')->name('logout'); 

    Route::get('/dashboard', 'memberController@dashboard')->name('dashboard'); 
    Route::get('/view','memberController@view')->name('view');
    Route::get('/edit','memberController@edit')->name('edit');
    Route::PUT('/update','memberController@update')->name('update');
    Route::post('/changepasswordmember','memberController@passwordupdate')->name('password.update');
    Route::get('/Watashiwa_Gym','memberController@gymview')->name('mygym');


    route::get('cardio','memberController@cardio')->name('cardio');
    route::get('weight','memberController@weight')->name('weight');
});

Route::prefix('gym')->name('gym.')->group(function()                //route for all gym
{
    Route::get('/login','Auth\gymLoginController@showLoginform')->name('login');    //login-page
    Route::Post('/login','Auth\gymLoginController@login')->name('login.submit');    //login
    Route::get('/logout','Auth\gymLoginController@gymlogout')->name('logout');      //logout
  
    Route::get('/activemembers','gymController@active_members')->name('active.members');
    Route::get('/inactivemembers','gymController@inactive_members')->name('inactive.members');
    Route::get('/dashboard','gymController@dashboard')->name('dashboard');

   Route::get('/memberview/{id}','gymController@memberview')->name('member.view');
   Route::get('/memberdelete/{id}','gymController@memberdelete')->name('member.delete');
   Route::POST('/memberpasswordupdate/{id}','gymController@memberpasswordupdate')->name('member.password.update');
   Route::get('/memberupdatepage/{id}','gymController@memberupdatepage')->name('member.update.page');
   Route::PUT('/memberupdate/{id}','gymController@memberupdate')->name('member.update'); 

   Route::get('/gymprofile','gymController@profile')->name('profile');
   Route::get('/admin','gymController@admin')->name('admin');
});

gym/resources/views/admin/addgym.blade.php
@extends('layouts.admin')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif

 
<div class="container" >
    <div style=margin-left:320px;>
    <div class="font-weight-bold "><h1>ADD NEW GYM</h1></div>
     <form action="{{route('admin.addgym')}}" method="post" enctype="multipart/form-data">
    @csrf  
        <div class="form-group col-md-6">                             
            <label for="name" class="font-weight-bold ">gym name:</label>
            <input type="text" name="name" class="form-control" >
            @error('name')<p style="color:red;">{{$message}}</p>@enderror
        </div>
        <div class="form-group col-md-6">                                           
            <label for="address" class="font-weight-bold ">gym address:</label>
            <input type="text" name="address" class="form-control">
            @error('address')<p style="color:red;">{{$message}}</p>@enderror
        </div>
        <div class="form-group col-md-6">                                 
            <label for="phone no" class="font-weight-bold ">phone no:</label>
            <input type="text" name="gymphno" class="form-control">
            @error('gymphno')<p style="color:red;">{{$message}}</p>@enderror
        </div>  
        <div class="form-group col-md-6">
            <label for="email" class="font-weight-bold ">email</label>  
            <input type="text" name="email" class="form-control">
            @error('email')<p style="color:red;">{{$message}}</p>@enderror
        </div>
        <div class="form-group col-md-6">                                        
            <label for="ownername" class="font-weight-bold ">owner Name:</label> 
            <input type="text" name="ownername" class="form-control">   
            @error('ownername')<p style="color:red;">{{$message}}</p>@enderror
        </div>
        <div class="form-group col-md-6">     
            <label for="owner pno" class="font-weight-bold ">owner phone no:</label>
            <input type="text" name="phno" class="form-control"> 
            @error('phno')<p style="color:red;">{{$message}}</p>@enderror         
        </div>  
        <div class="form-group col-md-6">                 
            <label for="owner pno" class="font-weight-bold ">Username:</label>    
            <input type="text" name="username" class="form-control">    
            @error('username')<p style="color:red;">{{$message}}</p>@enderror
        </div>             
        <div class="form-group col-md-6">         
            <label for="owner pno" class="font-weight-bold ">password:</label>   
            <input type="password" name="password" class="form-control">
            @error('password')<p style="color:red;">{{$message}}</p>@enderror
        </div>   
        <div class="form-group col-md-4">
            <label for="status" class="font-weight-bold ">Status:</label>
            <select name="status" id="active" class="form-control">
            <option selected value="1">active</option>
            <option value="0">inactive</option>
            </select>
            @error('status')<p style="color:red;">{{$message}}</p>@enderror
        </div>
        <div class="form-group col-md-8 ">
            <label for="images" class="font-weight-bold">Profile image:</label>         
            <input type="file" name="image">
            @error('image')<p style="color:red;">{{$message}}</p>@enderror
        </div>  

       
    
    <input type="submit" value="submit" style="margin-left:20%"class="btn btn-primary">
    </form>
    </div>
    </div>
    






@endsection

gym/resources/views/admin/allgym.blade.php
@extends('layouts.admin')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif


@if(count($gyms)>0)
    
<table class="table table-striped table-dark">
<thead>
<tr>
  <th scope="col">ID</th>
  <th scope="col">GYM NAME</th>
  <th scope="col">Joined AT</th>
  <th scope="col">Phone No</th>
  <th scope="col" >STATUS</th>
  <th scope="col">ACTION</th>
</tr>
</thead>
<tbody>

@foreach($gyms as $gym)
      <tr>
      <td scope="row">{{$gym->id}}</td>
      <td>{{$gym->name}}</td>  
      <td>{{$gym->created_at}}</td> 
      <td>{{$gym->phno}}</td>      
   
     <?php 
          $a= $gym->status;
          if($a==1)
          {$status="#00FF00";}
          elseif ($a==0) {
            $status="#FF0000";
          }
          else{
            $status="black";
          }
      ?>
     <td bgcolor="{{$status}}"></td>        
      <td>
      <a href="{{route('admin.gymview',$gym->id)}}" class="btn btn-primary" >view</a>
      <a href="{{route('admin.gym.allmembers',$gym->id)}}" class="btn btn-primary">view members</a>
      </td>
      </tr>
@endforeach
</tbody>
</table>


@else
<h1>No GYMS</h1>
@endif







@endsection

gym/resources/views/admin/allmembers.blade.php
@extends('layouts.admin')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif


    
<table class="table table-striped table-dark">
<thead>

<tr>
  <th scope="col">ID</th>
  <th scope="col">NAME</th>
  <th scope="col">Phone</th>
  <th scope="col">status</th>
  <th scope="col">ACTION</th>
</tr>
</thead>
<tbody>
    @foreach($members as $member)
      <tr>
      <td scope="row">{{$member->id}}</td>
      <td>{{$member->name}}</td>  
      <td>{{$member->phno}}</td>
      <?php 
          $a= $member->status;
          if($a==1)
          {$status="#00FF00";}
          elseif ($a==0) {
            $status="#FF0000";
          }
          else{
            $status="black";
          }
      ?>
     <td bgcolor="{{$status}}"></td>     
      <td><a href="{{route('admin.member.view',$member->id)}}" ><h4>view<h4></a></td>
      </tr>
@endforeach


</tbody>
</table>





@endsection

gym/resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif
<div class="container">
<h1>Welocome <b style="color:red">Admin</b></h1>
  <div class="pt-5"><label for="gyms">No of gyms =</label>
  {{$gym}}
  </div>
  <div>
  <label for="member">No of members =</label>
  {{$member}}
  </div>

</div>













@endsection

gym/resources/views/admin/future.blade.php
@extends('layouts.admin')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif

<div class="container">
    <h1 class="strong">Future Prospects</h1>
</div>

@endsection

gym/resources/views/admin/gymedit.blade.php
@extends('layouts.admin')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif

<div class="container" style="margin-left:5%">
<h1 class="font-weight-bold">{{$gym->name}} Update</h1>

 <form action="{{ route('admin.agym.update', $gym->id) }}" method="POST" enctype="multipart/form-data">

@csrf                              

{{method_field('PUT')}}

<label for="name" class="font-weight-bold">gym name:</label>
<input type="text" name="name" value="{{$gym->name}}" class="form-control col-md-4">
@error('name')<p style="color:red;">{{$message}}</p>@enderror
<br>     

<label for="address" class="font-weight-bold">gym address:</label>
<input type="text" name="address" value="{{$gym->address}}" class="form-control col-md-4">
@error('address')<p style="color:red;">{{$message}}</p>@enderror
<br>     

<label for="phone no" class="font-weight-bold">phone no:</label>
<input type="text" name="gymphno" value="{{$gym->gymphno}}" class="form-control col-md-4">
@error('gymphno')<p style="color:red;">{{$message}}</p>@enderror
<br>    

<label for="email" class="font-weight-bold">email:</label>  
<input type="text" name="email" value="{{$gym->email}}" class="form-control col-md-4">
@error('email')<p style="color:red;">{{$message}}</p>@enderror
<br>       

<label for="ownername" class="font-weight-bold">Owner Name:</label> 
<input type="text" name="ownername" value="{{$gym->ownername}}" class="form-control col-md-4">
@error('ownername')<p style="color:red;">{{$message}}</p>@enderror 
<br>   
      
<label for="owner pno" class="font-weight-bold">owner phone no:</label>
<input type="text" name="phno" value="{{$gym->phno}}" class="form-control col-md-4">          
@error('phno')<p style="color:red;">{{$message}}</p>@enderror
<br>       
            
<label for="owner pno" class="font-weight-bold">Username:</label>    
<input type="text" name="username" value="{{$gym->username}}" class="form-control col-md-4">    
@error('username')<p style="color:red;">{{$message}}</p>@enderror
<br>                          

<label for="status" class="font-weight-bold">Status</label>

 <select name="status" id="status"  class="form-control col-md-4">
    <?php
    if ($gym->status==1) {
        $a=1;$b="Active";
        $c=0;$d="Inactive";
    }else{
        $a=0;$b="Inactive";
        $c=1;$d="Active";
    }
  ?>
  <option value="{{ $a }}" selected>{{ $b }}</option>
  <option value="{{ $c }}">{{ $d }}</option>
</select>
@error('status')<p style="color:red;">{{$message}}</p>@enderror<br>

<label for="images" class="font-weight-bold">Profile image:</label>         
            <input type="file" name="image" multiple="multiple">
            @error('image')<p style="color:red;">{{$message}}</p>@enderror
<br>



<input type="submit" value="submit" class="btn btn-primary">


</form>
</div>


@endsection

gym/resources/views/admin/gymlist.blade.php
@extends('layouts.admin')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif

  
@if(count($gyms)>0)
<table class="table table-striped table-dark">
<thead>
<tr>
  <th scope="col">ID</th>
  <th scope="col" >GYM NAME</th>
  <th scope="col">Owner Name</th>
  <th scope="col">PHONE NO</th>
  <th scope="col" class="text-left">ACTION</th>
</tr>
</thead>
<tbody>

@foreach($gyms as $gym)
      <tr>
      <th scope="row">{{$gym->id}}</td>
      <td>{{$gym->name}}</td>
      <td>{{$gym->ownername}}</td>
      <td>{{$gym->phno}}</td>
      <td>
      <a href="{{route('admin.gymview',$gym->id)}}" class="btn btn-primary">view info</a>
      <a href="{{route('admin.gym.allmembers',$gym->id)}}" class="btn btn-primary">view members</a>
    </td>

      </tr>
@endforeach
</tbody>
</table>

<div style="margin-left:85%">
{{$gyms->links()}}
</div>
@else
<h1>No GYMS</h1>
@endif

@endsection

gym/resources/views/admin/gymview.blade.php
@extends('layouts.admin')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif


<style>
    input.hidden {
position: absolute;
left: -9999px;
}

#profile-image1 {
cursor: pointer;

width: 400px;
height: 400px;
border:2px solid #03b1ce ;}
.tital{ font-size:16px; font-weight:500;}
.bot-border{ border-bottom:1px black solid;
            width:50%;margin:10px 0  5px 0;
            }  
</style>


<div class="container">
    
    <div class="row">
            
            
           <div class="col-md-7 ">
    
    <div class="panel panel-default">
      <div class="panel-heading" style="margin-bottom:40px;">  <h4 >{{$gym->name}}</h4></div>
       <div class="panel-body">
           
        <div class="box box-info">
            
                <div class="box-body">
                         <div style="margin-left:80%">
                            @if($gym->image)
                            <div>
                            <img alt="User Pic" src="{{asset('storage/'.$gym->image)}}"id="profile-image1" class="img-circle img-responsive img"> 
                            </div>
                            @else
                            <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive img"> 
                                    
                            @endif   
                         </div>            
                  <br>
        
                  <!-- /input-group -->
</div>
<div style="margin-top:-75%">
             
                
    <div class="bot-border">   
    <div class="col-sm-5 col-xs-6 tital " >ID:</div>
    <div class="col-sm-7 col-xs-6 ">{{$gym->id}}</div>
</div>

<div class="bot-border">   
    <div class="col-sm-5 col-xs-6 tital " >Name:</div>
    <div class="col-sm-7 col-xs-6 ">{{$gym->name}}</div>
</div>
<div class="clearfix"></div>

<div class="bot-border">   
    <div class="col-sm-5 col-xs-6 tital " >Address:</div>
    <div class="col-sm-7">{{$gym->address}}</div>
</div>
<div class="clearfix"></div>
      
<div class="bot-border">
        <div class="col-sm-6 col-xs-6 tital " > Gym Phone no:</div>
        <div class="col-sm-7">{{$gym->gymphno}}</div>
    </div>
<div class="clearfix"></div>    

<div class="bot-border">
        <div class="col-sm-5 col-xs-6 tital " >Email:</div>
        <div class="col-sm-7">{{$gym->email}}</div>
    </div>
<div class="clearfix"></div>    

<div class="bot-border">
        <div class="col-sm-5 col-xs-6 tital " >Owner Name:</div>
        <div class="col-sm-7">{{$gym->ownername}}</div>
    </div>
<div class="clearfix"></div>   
<div class="bot-border">   
    <div class="col-sm-5 col-xs-6 tital " >Phone no:</div>
    <div class="col-sm-7 col-xs-6 ">{{$gym->phno}}</div>
</div> 
<div class="clearfix"></div>   

<div class="bot-border">
        <div class="col-sm-5 col-xs-6 tital "> Username:</div>
        <div class="col-sm-7">{{$gym->username}}</div>
    </div>
<div class="clearfix"></div>    

<div style="margin-bottom:10px;">
        <div class="col-sm-5 col-xs-6 tital "> status</div>
<div class="col-sm-7"> {{$status}}</div>

    </div>
<div class="clearfix"></div> 
<div>


<form action="{{ route('admin.gym.hakai',$gym->id)}}" method="POST">
    @method('DELETE')
    @csrf
    <a href="{{route('admin.agym.edit',$gym->id)}}" class="btn btn-primary">update</a>
    <button class="btn btn-danger">Delete GYM</button>
    </form>
</div>
<div class="clearfix"></div>  

<div style="margin-bottom:20px;">
<form action="{{route('admin.password.update',$gym->id)}}" method="Post">
           @csrf
           <br>
    <label for="password" class="col-sm-5 col-xs-6 tital ">Change Password</label> <br>
            
            <input type="password" name="password" id="password">
            <button type="submit" class="btn btn-primary">Change</button>
        </form>
    </div>
    
   

<div class="clearfix"></div> 
</div>
</div>
</div> 
        <script>
                  $(function() {
        $('#profile-image1').on('click', function() {
            $('#profile-image-upload').click();
        });
    });       
                  </script> 
           


@endsection

gym/resources/views/admin/memberview.blade.php
@extends('layouts.admin')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif

<style>
    input.hidden {
position: absolute;
left: -9999px;
}

#profile-image1 {
cursor: pointer;

width: 400px;
height: 400px;
border:2px solid #03b1ce ;}
.tital{ font-size:16px; font-weight:500;}
.bot-border{ border-bottom:1px black solid;  margin:15px 0  5px 0; width: 50%;}  
</style>


<div class="container">
    
    <div class="row">
            
            
           <div class="col-md-7 ">
    
    <div class="panel panel-default">
      <div class="panel-heading">  <h4 >Members Profile</h4></div>
       <div class="panel-body">
           
        <div class="box box-info">
            
                <div class="box-body">
                         <div style="margin-left:80%">
                            @if($member->image)
                            <div  style="align:center">
                            <img alt="User Pic" src="{{asset('storage/'.$member->image)}}"id="profile-image1" class="img-circle img-responsive"> 
                            </div>
                            @else
                            <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive"> 
                                    
                            @endif            
                  <br>           
                  <br>
        
       
</div>


<div style="margin-top:-70%">
                <div class="col-sm-6">
                <h4 style="color:#00b1b1;">{{$member->username}} </h4></span>
                <span><p>{{$member->gym->name}}</p></span>            
                </div>
                
             
<div class="bot-border"> 
    <div class="col-sm-5 col-xs-6 tital " >Name:</div>
    <div class="col-sm-7 col-xs-6 ">{{$member->name}}</div>
</div>
<div class="clearfix"></div>

<div class="bot-border">   
    <div class="col-sm-5 col-xs-6 tital " >Email:</div>
    <div class="col-sm-7">{{$member->email}}</div>
</div>
<div class="clearfix"></div>
      
<div class="bot-border">
        <div class="col-sm-5 col-xs-6 tital " >Phone no:</div>
        <div class="col-sm-7">{{$member->phno}}</div>
    </div>
<div class="clearfix"></div>    

<div class="bot-border">
        <div class="col-sm-5 col-xs-6 tital " >Gender:</div>
        <div class="col-sm-7">{{$member->gender}}</div>
    </div>
<div class="clearfix"></div>    

<div class="bot-border">
        <div class="col-sm-5 col-xs-6 tital " >Age:</div>
        <div class="col-sm-7">{{$member->age}}</div>
    </div>  
<div class="clearfix"></div>  

<div class="bot-border">
        <div class="col-sm-5 col-xs-6 tital "> Username:</div>
        <div class="col-sm-7">{{$member->username}}</div>
    </div>
<div class="clearfix"></div>    

<div style="margin-bottom:20px;">
        <div class="col-sm-5 col-xs-6 tital "> status</div>
<div class="col-sm-7"> {{$status}}</div>

    </div>

@endsection

gym/resources/views/admin/profile.blade.php
@extends('layouts.admin')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif

<div class="container">
<form action="{{route('admin.profile.update')}}" method="POST" >
  @csrf
  <div class="form-group">
  <label for="username"><h3>Admin Profile</h3></label><hr>
  <input type="text" readonly class="form-control-plaintext" value="{{$a->username}}" style=" font-size: 30px;">
  </div><br>
  <div class="form-group">
    <label for="Password">New Password</label>
    <input type="text" class="form-control" name="password" placeholder="enter new Password">
  </div>
  <button type="submit" class="btn btn-primary mb-2">Change Password</button>
</form>
</div>



@endsection