gym/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Auth::routes();
Route::get('/', function () {
    return view('welcome');
})->name('land');


//auth
Route::GET('/register','Auth\memberRegisterController@viewregisterform')->name('register');
Route::POST('/register','Auth\memberRegisterController@register')->name('register.submit');


Route::prefix('admin')->name('admin.')->group(function()                //route for all admin
{  
    Route::get('/login','Auth\adminLoginController@showLoginform')->name('login');
    Route::Post('/login','Auth\adminLoginController@login')->name('login.submit');
    Route::get('/logout','Auth\adminLoginController@adminlogout')->name('logout');   
    Route::get('/dashboard','adminController@dashboard')->name('dashboard');

    Route::get('/addgym','adminController@addg')->name('addg');         //addgym 
    Route::Post('/addgym','adminController@addgym')->name('addgym');

    //gym
    Route::get('/activegym','adminController@activegym')->name('activegym');    //list active gym
    Route::get('/allgym','adminController@allgym')->name('allgym');             //list all gym
    Route::get('/gymview/{gym}','adminController@gymview')->name('gymview');    //gymview
    Route::get('/edit/{gym}','adminController@gedit')->name('agym.edit');
    Route::PUT('/update/{gym}','adminController@gupdate')->name('agym.update');
    Route::post('/changepasswordgym/{id}','adminController@passwordupdate')->name('password.update');
    Route::DELETE('/deletegym/{id}','adminController@gymhakai')->name('gym.hakai');

    Route::get('/allmembers/{id}','adminController@allmembers')->name('gym.allmembers');
    Route::get('/memview/{member}','adminController@memberview')->name('member.view');

    Route::get('/adminprofile','adminController@profile')->name('profile');
    Route::post('/adminprofile1','adminController@profileupdate')->name('profile.update');
    Route::get('/future','adminController@future')->name('future');
  

});

Route::prefix('member')->name('member.')->group(function()                //route for all member
{
    Route::get('/login','Auth\memberLoginController@showLoginform')->name('login');
    Route::Post('/login','Auth\memberLoginController@login')->name('login.submit');
    Route::get('/logout','Auth\memberLoginController@memberlogout')->name('logout'); 

    Route::get('/dashboard', 'memberController@dashboard')->name('dashboard'); 
    Route::get('/view','memberController@view')->name('view');
    Route::get('/edit','memberController@edit')->name('edit');
    Route::PUT('/update','memberController@update')->name('update');
    Route::post('/changepasswordmember','memberController@passwordupdate')->name('password.update');
    Route::get('/Watashiwa_Gym','memberController@gymview')->name('mygym');


    route::get('cardio','memberController@cardio')->name('cardio');
    route::get('weight','memberController@weight')->name('weight');
});

Route::prefix('gym')->name('gym.')->group(function()                //route for all gym
{
    Route::get('/login','Auth\gymLoginController@showLoginform')->name('login');    //login-page
    Route::Post('/login','Auth\gymLoginController@login')->name('login.submit');    //login
    Route::get('/logout','Auth\gymLoginController@gymlogout')->name('logout');      //logout
  
    Route::get('/activemembers','gymController@active_members')->name('active.members');
    Route::get('/inactivemembers','gymController@inactive_members')->name('inactive.members');
    Route::get('/dashboard','gymController@dashboard')->name('dashboard');

   Route::get('/memberview/{id}','gymController@memberview')->name('member.view');
   Route::get('/memberdelete/{id}','gymController@memberdelete')->name('member.delete');
   Route::POST('/memberpasswordupdate/{id}','gymController@memberpasswordupdate')->name('member.password.update');
   Route::get('/memberupdatepage/{id}','gymController@memberupdatepage')->name('member.update.page');
   Route::PUT('/memberupdate/{id}','gymController@memberupdate')->name('member.update'); 

   Route::get('/gymprofile','gymController@profile')->name('profile');
   Route::get('/admin','gymController@admin')->name('admin');
});

gym/app/gym.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class gym extends Authenticatable
{
    use Notifiable;

    
    protected $guard='gym';
    protected $guarded=[];

   

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

        //activity
        public function Scopeactivegym($query)
        {
            return $query->where('status',1);
        }
        
        public function Scopeinactivegym($query)
        {
            return $query->where('status',0);
        }
 
        public function admins()                        //db relations
        {
            return $this->belongsTo(admin::class);
        }
    
        public function members()                               
        {
            return $this->hasMany(member::class);
        }
}

gym/app/Http/Controllers/gymController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\gym;
use App\admin;
use App\member;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Auth;
use Illuminate\Support\Facades\DB;

class gymController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth:gym');
    }

    public function active_members()
    {
        $id=auth::user()->id;
        $gym=gym::find($id);
        $members=$gym->members()->where('status',1)->paginate(8);
        return view('gym.activemembers',compact('members'));
    }
    
    public function inactive_members()
    {
        $id=auth::user()->id;
        $gym=gym::find($id);
        $members=$gym->members()->where('status',0)->paginate(8);
        return view('gym.activemembers',compact('members'));
    }
    public function dashboard()
    {
        $id=auth::user()->id;
        $gym=gym::find($id);
        $members=$gym->members()->where('status',2)->paginate(8);
        return view('gym.dashboard',compact('members'));
    }

    
    public function memberview($id)
    {
        $member=member::find($id);
        if ($member->status==1){$status="Active";}
        elseif($member->status==0){$status="inactive";}
        else{$status="Requesting";}  
        return view('gym.view_member',compact('member','status'));
    }
    public function memberdelete($id)
    {
        $member=member::find($id);
        $member->delete();
        return redirect()->route('gym.dashboard');
    }

    public function memberpasswordupdate(Request $request, $id)
    {
        $request->validate(
            [
                'password'=>'required'
            ]);

        $password = $request->input('password');        //hash password
        $newpassword= Hash::make($password);

        $data = member::find($id);
        $data->password= $newpassword;
        $data->save();
        return back();  
    }
    public function memberupdatepage($id)
    {
        $member=member::find($id);
        return view('gym.edit_member',compact('member'));
    }
    public function memberupdate(Request $request,$id)
    {
        $data = member::find($id);
      $this->validate($request,[     
                'email' => 'required|email',
                'name' => 'required',
                'phno' =>'required|numeric',
                'gender' =>'required',
                'age' => 'required|numeric|max:80',
                'username' => 'required'
            ]);
  
       
        $data->email = $request->input('email');
        $data->name=$request->input('name');
        $data->phno=$request->input('phno');
        $data->gender=$request->input('gender');
        $data->age=$request->input('age');
        $data->username=$request->input('username');
        $data->status=$request->input('status');
        $data->save();
        return back();
    }

    public function profile()
    {
        $gym=gym::find(Auth::user()->id);
        if ($gym->status==1) {
            $status="Active";
    }   else {
            $status="Inactive";
    }
        return view('gym.profile',compact('gym','status'));
    }

    public function admin()
    {
        $admin=admin::where('id',1)->get();
        return view('gym.admin',compact('admin'));
    }

 
}

gym/resources/views/gym/activemembers.blade.php
@extends('layouts.gym')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif

 

<table class="table table-striped table-dark">
<thead>
<tr>
  <th scope="col">ID</th>
  <th scope="col" >GYM NAME</th>
  <th scope="col">Gender</th>
  <th scope="col">PHONE NO</th>
  <th scope="col" class="text-left">ACTION</th>
</tr>
</thead>
<tbody>

@foreach($members as $member)
      <tr>
      <th scope="row">{{$member->id}}</td>
      <td>{{$member->name}}</td>
      <td>{{$member->gender}}</td>
      <td>{{$member->phno}}</td>
      <td>
      <a href="{{route('gym.member.view',$member->id)}}" class="btn btn-primary">view info</a>
    </td>

      </tr>
@endforeach
</tbody>
</table>

<div style="margin-left:85%">
{{$members->links()}}
</div>



@endsection

gym/resources/views/gym/admin.blade.php
@extends('layouts.gym')

@section('content') 

<h1>Contact admin for password change</h1>

<label for="email">Email</label>
{{$admin->email}}

<label for="phone no">Phone no </label>
{{$admin->phno}}

@endsection

gym/resources/views/gym/dashboard.blade.php
@extends('layouts.gym')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif

 

<table class="table table-striped table-dark">
<thead>
<tr>
  <th scope="col">ID</th>
  <th scope="col" >GYM NAME</th>
  <th scope="col">Gender</th>
  <th scope="col">PHONE NO</th>
  <th scope="col" class="text-left">ACTION</th>
</tr>
</thead>
<tbody>

@foreach($members as $member)
      <tr>
      <th scope="row">{{$member->id}}</td>
      <td>{{$member->name}}</td>
      <td>{{$member->gender}}</td>
      <td>{{$member->phno}}</td>
      <td>
      <a href="{{route('gym.member.view',$member->id)}}" class="btn btn-primary">view info</a>
    </td>

      </tr>
@endforeach
</tbody>
</table>

<div style="margin-left:85%">
{{$members->links()}}
</div>



@endsection

gym/resources/views/gym/edit_member.blade.php
@extends('layouts.gym')
@section('content')

<div class="container">

<h1>{{$member->name}}</h1>
    <form action="{{ route('gym.member.update',$member->id)}}" method="Post">
    
        @csrf                              
        {{method_field('PUT')}}
        
<label for="status" class="font-weight-bold">Status</label>

<select name="status" id="status"  class="form-control col-md-4">
   <?php
   if ($member->status==1) {
       $a=1;$b="Active";
       $c=0;$d="Inactive";
   }else{
       $a=0;$b="Inactive";
       $c=1;$d="Active";
   }
 ?>
 <option value="{{ $a }}" selected>{{ $b }}</option>
 <option value="{{ $c }}">{{ $d }}</option>
</select>

<br>

        
    
        
        <label for="name" class="font-weight-bold">Name:</label>
        <input type="text" name="name" value="{{$member->name}}" class="form-control col-md-4">
        @error('name')<p style="color:red;">{{$message}}</p>@enderror
        <br>
        <label for="email" class="font-weight-bold">Email:</label>
        <input type="text" name="email" value="{{$member->email}}" class="form-control col-md-4">
        @error('email')<p style="color:red;">{{$message}}</p>@enderror
        <br>                                              
        <label for="phone no" class="font-weight-bold">Phone no:</label>
        <input type="text" name="phno" value="{{$member->phno}}" class="form-control col-md-4">
        @error('phno')<p style="color:red;">{{$message}}</p>@enderror
        <br>  
        <label for="name" class="font-weight-bold">Gender:</label> 
    <select id="gender" name="gender" placeholder="{{$member->gender}} ">  
            <?php
              if ($member->gender=="male") {
                  $a="male";
                  $b="female";
              }else{
                  $a="female";
                  $b="male";
              }
            ?>
            <option value="{{ $a }}" selected>{{ $a }}</option>
            <option value="{{ $b }}">{{ $b }}</option>
          </select>
          @error('gender')<p style="color:red;">{{$message}}</p>@enderror
          <br>
    
    
        <label for="age" class="font-weight-bold">Age:</label>
        <input type="number" name="age" value="{{$member->age}}" class="form-control col-md-4">
        @error('age')<p style="color:red;">{{$message}}</p>@enderror
        <br>  
        <label for="username" class="font-weight-bold">Username:</label>
        <input type="text" name="username" value="{{$member->username}}" class="form-control col-md-4">
        @error('username')<p style="color:red;">{{$message}}</p>@enderror
        <br>  

        
        
        <input type="submit" value="update" class="btn btn-primary">
        </form>
    </div>


@endsection

gym/resources/views/gym/profile.blade.php
@extends('layouts.gym')

@section('content') 

@if (session('status'))
<div class="alert alert-success" role="alert">
{{ session('status') }}
</div>
@endif

<div class="container">

      <div class="panel-heading" style="margin-bottom:10px;">  <h4 >{{$gym->username}}</h4></div>

                    <style>
                        .label1{
                                font-size: 1.4em;
                                font-weight: bolder;
                                margin-top: 10px;
                        }
                        .text{
                            font-size: 1.1em;
                            background-color: #F0FFFF;
                            display: block;
                            border-bottom: 1px solid black;
                            width: 80%;
                            text-align: left;
                        }
                        .img{
                            
                            width: 400px;
                            height: 400px;
                            border-radius: 20px;
                            border: 1px solid black;
                            position: absolute;
                            right: 10%;
                            top: 10%;
                            box-sizing: border-box;
                            
                        }
                        .img-box{
                          float:right;
                               
                        }
                        .data{
                            float: left;
                            width: 400px;
                            margin-bottom: 30px;
                           
                        }
                    </style>
<div>
    <div class="img-box">
                    @if($gym->image)
                    <div>
                    <img alt="User Pic" src="{{asset('storage/'.$gym->image)}}"id="profile-image1" class="img-circle img-responsive img"> 
                    </div>
                    @else
                    <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive img"> 
                            
                    @endif    
    </div>
    
        
                  <!-- /input-group -->
</div>
<div class="data">
            
                
<div class="clearfix"><hr style="margin:5px 0 5px 0;">
    <div class=" label1" >ID:</div>
    <div class=" text">{{$gym->id}}</div>
</div>

<div class="clearfix"><hr style="margin:5px 0 5px 0;">
    <div class="label1 " >Name:</div>
    <div class="text">{{$gym->name}}</div>
</div>
<div class="clearfix"></div>

<div class="bot-border">   
    <div class="tital label1" >Address:</div>
    <div class=" text">{{$gym->address}}</div>
</div>
<div class="clearfix"></div>
      
<div class="bot-border">
        <div class=" label1" > Gym Phone no:</div>
        <div class="text">{{$gym->gymphno}}</div>
    </div>
<div class="clearfix"></div>    

<div class="bot-border">
        <div class=" label1" >Email:</div>
        <div class=" text">{{$gym->email}}</div>
    </div>
<div class="clearfix"></div>    

<div class="bot-border">
        <div class="tital label1" >Owner Name:</div>
        <div class=" text">{{$gym->ownername}}</div>
    </div>
<div class="clearfix"></div>   
<div class="clearfix"><hr style="margin:5px 0 5px 0;">
    <div class=" label1" >Phone no:</div>
    <div class="text">{{$gym->phno}}</div>
</div> 
<div class="clearfix"></div>   

<div class="bot-border">
        <div class=" label1"> Username:</div>
        <div class="text">{{$gym->username}}</div>
    </div>
<div class="clearfix"></div>    

<div class="bot-border">
        <div class="label1"> status</div>
<div class=" text"> {{$status}}</div>

    </div>
<div class="clearfix"></div> 

</div>
</div>



           


@endsection

gym/resources/views/gym/view_member.blade.php
@extends('layouts.gym')

@section('content') 


<style>

#profile-image1 {
cursor: pointer;

width: 400px;
height: 400px;
border:2px solid #03b1ce ;}
.tital{ font-size:16px; font-weight:500;}
.bot-border{ border-bottom:1px #f8f8f8 solid;  margin:5px 0  5px 0}  

           
      
                        .data{
                            float: left;
                           
                        }
                        .img{
                            float:right;
                            margin-right: 20%;
                            
                        }
             

</style>


<div class="container">
    

            
      <div class="panel-heading">  <h4 >Members Profile</h4></div>
  
           
       
            
     <div> {{--main block--}}         
                    <div class="img">
                            @if($member->image)
                            <div  style="align:center">
                            <img alt="User Pic" src="{{asset('storage/'.$member->image)}}"id="profile-image1" class="img-circle img-responsive"> 
                            </div>
                            @else
                            <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive"> 
                                    
                            @endif
                    </div>
               
                         


<div class="data">{{--datablock--}}
                
<h4 style="color:#00b1b1;">{{$member->username}} </h4>        
                
                
             
<div class="clearfix"><hr style="margin:5px 0 5px 0;">
    <div class="tital">Name:</div>
    <div >{{$member->name}}</div>
</div>
<div class="clearfix"></div>

<div class="bot-border">   
    <div class=" tital " >Email:</div>
    <div >{{$member->email}}</div>
</div>
<div class="clearfix"></div>
      
<div class="bot-border">
        <div class="tital " >Phone no:</div>
        <div >{{$member->phno}}</div>
    </div>
<div class="clearfix"></div>    

<div class="bot-border">
        <div class="tital " >Gender:</div>
        <div >{{$member->gender}}</div>
    </div>
<div class="clearfix"></div>    

<div class="bot-border">
        <div class="tital " >Age:</div>
        <div >{{$member->age}}</div>
    </div>
<div class="clearfix"></div>    

<div class="bot-border">
        <div class="tital "> Username:</div>
        <div >{{$member->username}}</div>
    </div>
<div class="clearfix"></div>    

<div class="bot-border">
        <div class="tital "> status</div>
<div > {{$status}}</div>

    </div>
<div class="clearfix"></div> 

<a href="{{route('gym.member.update.page',$member->id)}}" class="btn btn-primary">Update</a>
<a href="{{route('gym.member.delete',$member->id)}}" class="btn btn-danger ml-3">Delete</a>
<div class="clearfix"></div>  

<div class="bot-border">
<form action="{{route('gym.member.password.update', $member->id)}}" method="Post">
       @csrf
       <br>
<label for="password" class="tital ">Change Password</label> <br>
        
        <input type="password" name="password" id="password">
        <button type="submit" class="btn btn-primary">Change</button>
    </form>
</div>

<div class="clearfix"></div> 

</div>{{--data--}}
</div>{{--main block--}}
</div>{{-- Container --}}

           



@endsection