gym/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Auth::routes();
Route::get('/', function () {
    return view('welcome');
})->name('land');


//auth
Route::GET('/register','Auth\memberRegisterController@viewregisterform')->name('register');
Route::POST('/register','Auth\memberRegisterController@register')->name('register.submit');


Route::prefix('admin')->name('admin.')->group(function()                //route for all admin
{  
    Route::get('/login','Auth\adminLoginController@showLoginform')->name('login');
    Route::Post('/login','Auth\adminLoginController@login')->name('login.submit');
    Route::get('/logout','Auth\adminLoginController@adminlogout')->name('logout');   
    Route::get('/dashboard','adminController@dashboard')->name('dashboard');

    Route::get('/addgym','adminController@addg')->name('addg');         //addgym 
    Route::Post('/addgym','adminController@addgym')->name('addgym');

    //gym
    Route::get('/activegym','adminController@activegym')->name('activegym');    //list active gym
    Route::get('/allgym','adminController@allgym')->name('allgym');             //list all gym
    Route::get('/gymview/{gym}','adminController@gymview')->name('gymview');    //gymview
    Route::get('/edit/{gym}','adminController@gedit')->name('agym.edit');
    Route::PUT('/update/{gym}','adminController@gupdate')->name('agym.update');
    Route::post('/changepasswordgym/{id}','adminController@passwordupdate')->name('password.update');
    Route::DELETE('/deletegym/{id}','adminController@gymhakai')->name('gym.hakai');

    Route::get('/allmembers/{id}','adminController@allmembers')->name('gym.allmembers');
    Route::get('/memview/{member}','adminController@memberview')->name('member.view');

    Route::get('/adminprofile','adminController@profile')->name('profile');
    Route::post('/adminprofile1','adminController@profileupdate')->name('profile.update');
    Route::get('/future','adminController@future')->name('future');
  

});

Route::prefix('member')->name('member.')->group(function()                //route for all member
{
    Route::get('/login','Auth\memberLoginController@showLoginform')->name('login');
    Route::Post('/login','Auth\memberLoginController@login')->name('login.submit');
    Route::get('/logout','Auth\memberLoginController@memberlogout')->name('logout'); 

    Route::get('/dashboard', 'memberController@dashboard')->name('dashboard'); 
    Route::get('/view','memberController@view')->name('view');
    Route::get('/edit','memberController@edit')->name('edit');
    Route::PUT('/update','memberController@update')->name('update');
    Route::post('/changepasswordmember','memberController@passwordupdate')->name('password.update');
    Route::get('/Watashiwa_Gym','memberController@gymview')->name('mygym');


    route::get('cardio','memberController@cardio')->name('cardio');
    route::get('weight','memberController@weight')->name('weight');
});

Route::prefix('gym')->name('gym.')->group(function()                //route for all gym
{
    Route::get('/login','Auth\gymLoginController@showLoginform')->name('login');    //login-page
    Route::Post('/login','Auth\gymLoginController@login')->name('login.submit');    //login
    Route::get('/logout','Auth\gymLoginController@gymlogout')->name('logout');      //logout
  
    Route::get('/activemembers','gymController@active_members')->name('active.members');
    Route::get('/inactivemembers','gymController@inactive_members')->name('inactive.members');
    Route::get('/dashboard','gymController@dashboard')->name('dashboard');

   Route::get('/memberview/{id}','gymController@memberview')->name('member.view');
   Route::get('/memberdelete/{id}','gymController@memberdelete')->name('member.delete');
   Route::POST('/memberpasswordupdate/{id}','gymController@memberpasswordupdate')->name('member.password.update');
   Route::get('/memberupdatepage/{id}','gymController@memberupdatepage')->name('member.update.page');
   Route::PUT('/memberupdate/{id}','gymController@memberupdate')->name('member.update'); 

   Route::get('/gymprofile','gymController@profile')->name('profile');
   Route::get('/admin','gymController@admin')->name('admin');
});

gym/resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>OURBOROUS GYM</title>
        <link href="{{ asset('admincss/styles.css') }}" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
    </head>

    <body class="sb-nav-fixed" style="background-color:rgb(192,192,192);">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="{{route('admin.dashboard')}}">Ourborous GYM</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button
            ><!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                     
                    <a class="dropdown-item" href="{{route('admin.logout')}}">Logout</a>
                    </div>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="{{route('admin.dashboard')}}"
                                ><div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard</a
                            >
                            <div class="sb-sidenav-menu-heading">GYM</div>
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts"
                                ><div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                 GYMS
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div
                            ></a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{{route('admin.activegym')}}">Active GYM</a>
                                <a class="nav-link" href="{{route('admin.allgym')}}">GYM History</a></nav>
                            </div>
{{-- .................................................................... --}}
                        

                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages"
                                ><div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                               Payment
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div
                            >
                        </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link" href="{{route('admin.future')}}">paymet</a>  
                                    <a class="nav-link" href="{{route('admin.future')}}">payment records</a>  
                                </nav>
                            </div>

{{-- .................................................................... --}}                                
                            <div class="sb-sidenav-menu-heading">Addons</div>
                            <a class="nav-link" href={{route('admin.addg')}}
                                ><div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Add GYM</a
                        ><a class="nav-link" href="{{route('admin.profile')}}"
                                ><div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Profile</a
                            >
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                       <h2>{{ Auth::user()->username }}</h2>
                                        </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    @yield('content')





                </main>
                <footer class="py-4 mt-auto" style="color:white;background-color:black">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2019</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{{ asset('adminjs/scripts.js')}}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    
    </body>
</html>

gym/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>OURBOROUS GYM</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <style>
    .ram{
      padding: 0px 20px;

    }
    .fot{
      border-top:4px solid rgba(200,0,0,0.9);
    }
    .fot-color{
      background-color: black;
      color: whitesmoke;
      position: relative;
      bottom:0px;
      margin-top: 50px;
    }
    
    .push{
        margin-top: 4%;
        margin-bottom:8.4%;
    }
  </style>
</head>
<body style="background-color:#212121">
    

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<a class="navbar-brand" href="{{route('land')}}">OURBOROUS GYM</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText" style="margin-left:60%">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active ram">
          <a class="nav-link" href="{{route('land')}}">Home <span class="sr-only">(current)</span></a>
        </li>
       
            <li class="nav-item ram">
              <a class="nav-link" href="{{route('register')}}">register</a></li>
              
      <li class="nav-item dropdown ram">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  login
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{{route('admin.login')}}">Admin login</a>
                  <a class="dropdown-item" href="{{route('gym.login')}}">GYM login</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{{route('member.login')}}" style="color:red" >Member login</a>
                </div>
              </li>
      </ul>
    </div>
  </nav>
<main>
    @yield('content')

</main>

<!-- Footer -->
<footer class="page-footer font-small color-dark pt-4 fot fot-color" style="color:white" >

  <!-- Footer Elements -->
  <div class="container">

    <!-- Call to action -->
    <ul class="list-unstyled list-inline text-center py-2">
      <li class="list-inline-item">
        <h5 class="mb-1">Register for free</h5>
      </li>
      <li class="list-inline-item">
        <a href="{{route('register')}}" class="btn btn-outline-white btn-rounded">Sign up!</a>
      </li>
    </ul>
    <!-- Call to action -->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> Ourborous.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->




</footer>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

gym/resources/views/layouts/gym.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>{{Auth::user()->name}}</title>
        <link href="{{ asset('admincss/styles.css') }}" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
    </head>

    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="{{route('gym.dashboard')}}">{{auth::user()->name}}</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button
            ><!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                     
                        <a class="dropdown-item" href="{{route('gym.logout')}}">Logout</a>
                    </div>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="{{route('gym.dashboard')}}"
                                ><div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard</a
                            >
                            <div class="sb-sidenav-menu-heading">Members</div>
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts"
                                ><div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                 Members
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div
                            ></a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{{route('gym.active.members')}}">Active members</a>
                                <a class="nav-link" href="{{route('gym.inactive.members')}}">Inactive members</a></nav>
                            </div>
{{-- .................................................................... --}}
                        

                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages"
                                ><div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Profile
                         <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link" href="{{route('gym.profile')}}">GYM Profile</a>  
                                  
                                </nav>
                            </div>


                            
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                       <h3>{{ Auth::user()->name }}</h3>
                                        </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    @yield('content')

                </main>     
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{{ asset('adminjs/scripts.js')}}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    
    </body>
</html>

gym/resources/views/layouts/member.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

    <title>{{Auth::user()->gym->name }}</title>
        <link href="{{ asset('admincss/styles.css') }}" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
    </head>

    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="{{route('member.dashboard')}}">{{ Auth::user()->name }}</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button
            ><!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                     
                        <a class="dropdown-item" href="{{route('member.logout')}}">Logout</a>
                    </div>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="{{route('member.dashboard')}}"
                                ><div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard</a
                            >
                            <div class="sb-sidenav-menu-heading">Training</div>
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts"
                                ><div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                 Workouts
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div
                            ></a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{{route('member.cardio')}}">Cardio</a>
                                    <a class="nav-link" href="{{route('member.weight')}}">Weights</a>
                                    
                            </div>
{{-- .................................................................... --}}
                        

                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages"
                                ><div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Profile
                         <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link" href="{{route("member.view")}}">My Profile</a>  
                                <a class="nav-link" href="{{route("member.mygym")}}">My Gym</a>  
                                </nav>
                            </div>


                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                       <h3>{{ Auth::user()->name }}</h3>
                                        </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    @yield('content')





                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; OURBOROUS 2020</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{{ asset('adminjs/scripts.js')}}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    
    </body>
</html>